Repository Engineering-Excellence/CineVerse, pull requests merged in 2023-09, with the labels that each got.

#22 feat(crawling): Add Crawling
  pom.xml
  src/main/java/kr/co/dbcs/controller/HomeController.java
  src/main/java/kr/co/dbcs/model/AuthVO.java
  src/main/java/kr/co/dbcs/model/MovieVO.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/test/java/kr/co/dbcs/config/DataSourceTest.java
Labels: enhancement

#23 feat: add chat prototype
  pom.xml
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/AdminController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/SocketController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/model/ChatMessageDTO.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/resources/log4j2.properties
  src/main/resources/sql/TheaterRelated.sql
  src/main/resources/sql/foodReleated.sql
  src/main/resources/sql/movieRelated.sql
  src/main/webapp/WEB-INF/js/sockjs.js
  src/main/webapp/WEB-INF/js/stomp.min.js
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/member/chatTest.jsp
  src/main/webapp/WEB-INF/views/member/movie_api_example.txt
Labels: enhancement

#26 feat: add chat
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/SocketController.java
  src/main/webapp/WEB-INF/css/member/chat.css
  src/main/webapp/WEB-INF/css/member/chat.scss
  src/main/webapp/WEB-INF/js/member/chat.js
  src/main/webapp/WEB-INF/views/member/chat.html
  src/main/webapp/WEB-INF/views/member/chat.jsp
  src/main/webapp/WEB-INF/views/member/chatTest.jsp
Labels: enhancement

#27 fix(crawling): add movie info
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/model/MovieVO.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/js/index.js
  src/main/webapp/WEB-INF/js/login.js
  src/main/webapp/WEB-INF/js/member/chat.js
Labels: documentation

#28 FIX : CHAT BUG FIX
  src/main/resources/sql/TheaterRelated.sql
  src/main/resources/sql/auth.sql
  src/main/resources/sql/foodReleated.sql
  src/main/resources/sql/member.sql
  src/main/resources/sql/movieRelated.sql
  src/main/webapp/WEB-INF/js/member/chat.js
Labels: bug

#29 design: movieView view add
  src/main/webapp/WEB-INF/css/member/movieView.css
  src/main/webapp/WEB-INF/css/member/movieView.scss
  src/main/webapp/WEB-INF/views/member/home.jsp
  src/main/webapp/WEB-INF/views/member/movieDetail.jsp
  src/main/webapp/WEB-INF/views/member/movieView.jsp
Labels: enhancement

#30 design: movieList view
  src/main/webapp/WEB-INF/css/member/movieList.css
  src/main/webapp/WEB-INF/css/member/movieList.scss
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/views/member/movieList.jsp
Labels: enhancement

#31 feat: add movieList page's data
  src/main/webapp/WEB-INF/css/member/movieList.css
  src/main/webapp/WEB-INF/css/member/movieList.scss
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/views/member/movieList.jsp
Labels: enhancement

#32 fix: fix movie loved button bug
  src/main/webapp/WEB-INF/css/member/movieList.css
  src/main/webapp/WEB-INF/css/member/movieList.scss
  src/main/webapp/WEB-INF/js/member/movieList.js
Labels: bug

#33 Bnbu
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/index.scss
  src/main/webapp/WEB-INF/css/member/movieList.css
  src/main/webapp/WEB-INF/css/member/movieList.scss
  src/main/webapp/WEB-INF/css/member/movieView.css
  src/main/webapp/WEB-INF/css/member/movieView.scss
  src/main/webapp/WEB-INF/css/member/userHeader.css
  src/main/webapp/WEB-INF/css/member/userHeader.scss
  src/main/webapp/WEB-INF/js/member/chat.js
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/js/member/movieView.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/chat.jsp
  src/main/webapp/WEB-INF/views/member/home.jsp
  src/main/webapp/WEB-INF/views/member/movieView.jsp
  src/main/webapp/WEB-INF/views/member/movie_api_example.txt
Labels: enhancement

#35 fix: fix chat automatically scroll to bottom
  src/main/webapp/WEB-INF/js/member/chat.js
Labels: enhancement

#36 feat(view): add ticket view
  src/main/java/kr/co/dbcs/controller/SocketController.java
  src/main/java/kr/co/dbcs/controller/TicketController.java
  src/main/java/kr/co/dbcs/model/MegaboxVO.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/animate.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-icons.css
  src/main/webapp/WEB-INF/css/boxicons.css
  src/main/webapp/WEB-INF/css/glightbox.css
  src/main/webapp/WEB-INF/css/member/ticket.css
  src/main/webapp/WEB-INF/css/member/ticket.scss
  src/main/webapp/WEB-INF/css/reset.css
  src/main/webapp/WEB-INF/css/style.css
  src/main/webapp/WEB-INF/js/member/ticket.js
  src/main/webapp/WEB-INF/views/layouts/footer.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/home.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
Labels: enhancement

#37 add missing VO
  src/main/java/kr/co/dbcs/model/MegaboxVO.java
Labels: bug

#38 feat : add box office ranking in index and update chat
  src/main/java/kr/co/dbcs/controller/SocketController.java
  src/main/java/kr/co/dbcs/controller/StatController.java
  src/main/java/kr/co/dbcs/model/ChatMessageDTO.java
  src/main/java/kr/co/dbcs/service/StatService.java
  src/main/java/kr/co/dbcs/service/StatServiceImpl.java
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/member/chat.css
  src/main/webapp/WEB-INF/css/member/chat.scss
  src/main/webapp/WEB-INF/css/member/userHeader.css
  src/main/webapp/WEB-INF/css/member/userHeader.scss
  src/main/webapp/WEB-INF/images/person-solid.svg
  src/main/webapp/WEB-INF/js/index.js
  src/main/webapp/WEB-INF/js/member/chat.js
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/js/member/movieSearch.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/chat.html
  src/main/webapp/WEB-INF/views/member/chat.jsp
  src/main/webapp/WEB-INF/views/stat/main.jsp
Labels: enhancement

#39 feat: add movie loved
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/mapper/LovedMapper.java
  src/main/java/kr/co/dbcs/model/LovedVO.java
  src/main/java/kr/co/dbcs/provider/LovedSqlProvider.java
  src/main/java/kr/co/dbcs/service/LovedService.java
  src/main/java/kr/co/dbcs/service/LovedServiceImpl.java
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/js/member/movieSearch.js
  src/main/webapp/WEB-INF/views/member/movieList.jsp
  src/main/webapp/WEB-INF/views/member/movieSearch.jsp
  src/main/webapp/WEB-INF/views/stat/main.jsp
Labels: enhancement

#41 style(login): add scss for login page
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/index.scss
  src/main/webapp/WEB-INF/css/login.css
  src/main/webapp/WEB-INF/css/login.scss
  src/main/webapp/WEB-INF/css/main.css
  src/main/webapp/WEB-INF/css/main.scss
  src/main/webapp/WEB-INF/js/login.js
  src/main/webapp/WEB-INF/js/member/chat.js
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/js/member/movieSearch.js
  src/main/webapp/WEB-INF/js/member/movieView.js
  src/main/webapp/WEB-INF/js/member/ticket.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
Labels: enhancement

#42 add memberInfo, view
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/member/myPage.css
  src/main/webapp/WEB-INF/css/member/myPage.scss
  src/main/webapp/WEB-INF/js/member/memberMypage.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/home.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#43 feat: send crawl JSON to view
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/model/MovieVO.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/index.scss
  src/main/webapp/WEB-INF/css/login.css
  src/main/webapp/WEB-INF/css/login.scss
  src/main/webapp/WEB-INF/css/member/chat.css.map
  src/main/webapp/WEB-INF/css/member/chat.scss
  src/main/webapp/WEB-INF/css/member/header.css.map
  src/main/webapp/WEB-INF/css/member/header.scss
  src/main/webapp/WEB-INF/css/member/join.css.map
  src/main/webapp/WEB-INF/css/member/join.scss
  src/main/webapp/WEB-INF/css/member/login.css.map
  src/main/webapp/WEB-INF/css/member/login.scss
  src/main/webapp/WEB-INF/css/member/movieDetail.css.map
  src/main/webapp/WEB-INF/css/member/movieDetail.scss
  src/main/webapp/WEB-INF/css/member/movieList.css.map
  src/main/webapp/WEB-INF/css/member/movieList.scss
  src/main/webapp/WEB-INF/css/member/movieView.css.map
  src/main/webapp/WEB-INF/css/member/movieView.scss
  src/main/webapp/WEB-INF/css/member/myPage.css
  src/main/webapp/WEB-INF/css/member/myPage.css.map
  src/main/webapp/WEB-INF/css/member/myPage.scss
  src/main/webapp/WEB-INF/css/member/ticket.css
  src/main/webapp/WEB-INF/css/member/ticket.css.map
  src/main/webapp/WEB-INF/css/member/ticket.scss
  src/main/webapp/WEB-INF/css/member/userHeader.css
  src/main/webapp/WEB-INF/css/member/userHeader.css.map
  src/main/webapp/WEB-INF/css/member/userHeader.scss
  src/main/webapp/WEB-INF/css/member/userMain.css.map
  src/main/webapp/WEB-INF/css/member/userMain.scss
  src/main/webapp/WEB-INF/js/member/ticket.js
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
Labels: enhancement

#44 feat: board, reply CRUD
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/controller/ReplyController.java
  src/main/java/kr/co/dbcs/mapper/BoardMapper.java
  src/main/java/kr/co/dbcs/mapper/ReplyMapper.java
  src/main/java/kr/co/dbcs/model/BoardVO.java
  src/main/java/kr/co/dbcs/model/ReplyVO.java
  src/main/java/kr/co/dbcs/provider/BoardSqlProvider.java
  src/main/java/kr/co/dbcs/provider/ReplySqlProvider.java
  src/main/java/kr/co/dbcs/service/BoardService.java
  src/main/java/kr/co/dbcs/service/BoardServiceImpl.java
  src/main/java/kr/co/dbcs/service/ReplyService.java
  src/main/java/kr/co/dbcs/service/ReplyServiceImpl.java
  src/main/webapp/WEB-INF/css/board/list.css
  src/main/webapp/WEB-INF/css/board/list.scss
  src/main/webapp/WEB-INF/css/board/write.css
  src/main/webapp/WEB-INF/css/board/write.scss
  src/main/webapp/WEB-INF/js/board/boardWrite.js
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/update.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
  src/main/webapp/WEB-INF/views/member/boardList.jsp
  src/main/webapp/WEB-INF/views/member/home.jsp
Labels: enhancement

#45 add Member Mypage
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/webapp/WEB-INF/css/member/myPage.css
  src/main/webapp/WEB-INF/js/member/memberMypage.js
  src/main/webapp/WEB-INF/js/member/note.css
  src/main/webapp/WEB-INF/js/member/note.js
  src/main/webapp/WEB-INF/views/member/note.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#46 fix chat css and add controller branch to movie/ticket in home.jsp
  src/main/webapp/WEB-INF/css/board/list.css
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/index.scss
  src/main/webapp/WEB-INF/css/login.css
  src/main/webapp/WEB-INF/css/login.scss
  src/main/webapp/WEB-INF/css/member/chat.css
  src/main/webapp/WEB-INF/css/member/chat.css.map
  src/main/webapp/WEB-INF/css/member/chat.scss
  src/main/webapp/WEB-INF/css/member/header.css.map
  src/main/webapp/WEB-INF/css/member/header.scss
  src/main/webapp/WEB-INF/css/member/login.css.map
  src/main/webapp/WEB-INF/css/member/login.scss
  src/main/webapp/WEB-INF/css/member/stat.scss
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/member/home.jsp
Labels: enhancement

#48 feat: add loved list in mypage and recommendation list in main page.
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/index.scss
  src/main/webapp/WEB-INF/images/test.jpg
  src/main/webapp/WEB-INF/js/index.js
  src/main/webapp/WEB-INF/js/member/memberMypage.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/member/movieView.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#49 design: board design
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/controller/ReplyController.java
  src/main/webapp/WEB-INF/css/board/list.css
  src/main/webapp/WEB-INF/css/board/list.scss
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/update.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
Labels: enhancement

#51 add ticket page
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/member/ticket.css
  src/main/webapp/WEB-INF/css/member/ticket.css.map
  src/main/webapp/WEB-INF/css/member/ticket.scss
  src/main/webapp/WEB-INF/js/member/ticket.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
Labels: enhancement

#57 fix : add ticketing page information message
  src/main/webapp/WEB-INF/js/member/ticket.js
Labels: bug

#58 feat: add write board, reply in my page
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/BoardMapper.java
  src/main/java/kr/co/dbcs/mapper/ReplyMapper.java
  src/main/java/kr/co/dbcs/provider/BoardSqlProvider.java
  src/main/java/kr/co/dbcs/provider/ReplySqlProvider.java
  src/main/java/kr/co/dbcs/service/BoardService.java
  src/main/java/kr/co/dbcs/service/BoardServiceImpl.java
  src/main/java/kr/co/dbcs/service/ReplyService.java
  src/main/java/kr/co/dbcs/service/ReplyServiceImpl.java
  src/main/webapp/WEB-INF/css/member/myPage.css
  src/main/webapp/WEB-INF/css/member/myPage.css.map
  src/main/webapp/WEB-INF/css/member/myPage.scss
  src/main/webapp/WEB-INF/css/member/userHeader.css
  src/main/webapp/WEB-INF/css/member/userHeader.css.map
  src/main/webapp/WEB-INF/css/member/userHeader.scss
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#60 feat(member): change member profile image
  src/main/java/kr/co/dbcs/config/RootConfig.java
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/js/member/update.js
  src/main/webapp/WEB-INF/views/member/update.jsp
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/board/list.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/board/write.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-grid.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-grid.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-grid.rtl.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-grid.rtl.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-reboot.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-reboot.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-reboot.rtl.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-reboot.rtl.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-utilities.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-utilities.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-utilities.rtl.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap-utilities.rtl.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap.rtl.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/bootstrap/bootstrap.rtl.min.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/index.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/login.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/chat.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/header.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/join.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/login.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/movieDetail.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/movieList.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/movieView.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/myPage.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/ticket.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/userHeader.css.map
  target/Finale-1.0-SNAPSHOT/WEB-INF/css/member/userMain.css.map
Labels: enhancement

#61 feat(member): delete profile image
  pom.xml
  src/main/java/kr/co/dbcs/controller/AdminController.java
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/controller/HomeController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/controller/ReplyController.java
  src/main/java/kr/co/dbcs/controller/SocketController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/BoardService.java
  src/main/java/kr/co/dbcs/service/BoardServiceImpl.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/java/kr/co/dbcs/service/ReplyServiceImpl.java
  src/main/webapp/WEB-INF/css/reset.css
  src/main/webapp/WEB-INF/js/member/update.js
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#62 test(jython): junit test for jython crawling
  pom.xml
  src/main/java/kr/co/dbcs/model/AuthVO.java
  src/main/java/kr/co/dbcs/model/BoardVO.java
  src/main/java/kr/co/dbcs/model/MegaboxVO.java
  src/main/java/kr/co/dbcs/model/MemberImgVO.java
  src/main/java/kr/co/dbcs/model/ReplyVO.java
  src/test/java/kr/co/dbcs/jython/JythonCrawlTest.java
Labels: help wanted

#64 feat(crawl): add crawler for lotte cinema info
  pom.xml
  src/main/java/kr/co/dbcs/aop/LogAdvice.java
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/model/CustomUser.java
  src/main/java/kr/co/dbcs/model/LotteCinemaVO.java
  src/main/java/kr/co/dbcs/model/MovieVO.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/test/java/kr/co/dbcs/jython/JythonCrawlerTest.java
Labels: enhancement

#65 design: board view
  src/main/webapp/WEB-INF/css/board/list.css
  src/main/webapp/WEB-INF/css/board/list.css.map
  src/main/webapp/WEB-INF/css/board/list.scss
  src/main/webapp/WEB-INF/css/board/view.css
  src/main/webapp/WEB-INF/css/board/view.scss
  src/main/webapp/WEB-INF/css/board/write.css
  src/main/webapp/WEB-INF/css/board/write.css.map
  src/main/webapp/WEB-INF/css/board/write.scss
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/update.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
Labels: enhancement

#66 fix(member): sign in hot-fix
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
Labels: bug

#67 fix: mypage hot fix
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: bug

#70 feat: add loved button in movie view page
  src/main/webapp/WEB-INF/css/member/chat.css
  src/main/webapp/WEB-INF/css/member/chat.css.map
  src/main/webapp/WEB-INF/css/member/chat.scss
  src/main/webapp/WEB-INF/css/member/movieView.css
  src/main/webapp/WEB-INF/css/member/movieView.css.map
  src/main/webapp/WEB-INF/css/member/movieView.scss
  src/main/webapp/WEB-INF/js/index.js
  src/main/webapp/WEB-INF/js/member/movieList.js
  src/main/webapp/WEB-INF/js/member/movieView.js
  src/main/webapp/WEB-INF/views/member/chat.jsp
  src/main/webapp/WEB-INF/views/member/movieView.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#72 feat: 메일 인증, 게시판 버그 수정
  src/main/java/kr/co/dbcs/config/MailConfig.java
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/config/WebConfig.java
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/controller/MailServiceRestController.java
  src/main/java/kr/co/dbcs/service/MailService.java
  src/main/java/kr/co/dbcs/service/MailServiceImpl.java
  src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#73 feat(board): add backend logic for paging board list
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/mapper/BoardMapper.java
  src/main/java/kr/co/dbcs/model/BoardList.java
  src/main/java/kr/co/dbcs/provider/BoardSqlProvider.java
  src/main/java/kr/co/dbcs/service/BoardService.java
  src/main/java/kr/co/dbcs/service/BoardServiceImpl.java
  src/main/java/kr/co/dbcs/service/MailService.java
  src/main/java/kr/co/dbcs/service/MailServiceImpl.java
  src/main/resources/sql/memberImg.sql
  src/main/webapp/WEB-INF/views/board/list.jsp
Labels: enhancement

#75 feat(board): add write, list notice
  src/main/java/kr/co/dbcs/controller/AdminController.java
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/NoteController.java
  src/main/java/kr/co/dbcs/mapper/BoardMapper.java
  src/main/java/kr/co/dbcs/mapper/NoteMapper.java
  src/main/java/kr/co/dbcs/model/BoardList.java
  src/main/java/kr/co/dbcs/model/BoardVO.java
  src/main/java/kr/co/dbcs/provider/BoardSqlProvider.java
  src/main/java/kr/co/dbcs/provider/NoteSqlProvider.java
  src/main/java/kr/co/dbcs/service/BoardService.java
  src/main/java/kr/co/dbcs/service/BoardServiceImpl.java
  src/main/java/kr/co/dbcs/service/NoteService.java
  src/main/java/kr/co/dbcs/service/NoteServiceImpl.java
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.min.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.rtl.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.rtl.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.rtl.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-grid.rtl.min.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.min.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.rtl.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.rtl.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.rtl.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-reboot.rtl.min.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.min.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.rtl.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.rtl.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.rtl.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap-utilities.rtl.min.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap.rtl.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap.rtl.css.map
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap.rtl.min.css
  src/main/webapp/WEB-INF/css/bootstrap/bootstrap.rtl.min.css.map
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
Labels: enhancement

#77 add update member after swal
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/webapp/WEB-INF/js/member/update.js
  src/main/webapp/WEB-INF/views/member/note.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
  src/main/webapp/WEB-INF/views/note/noteForm.jsp
Labels: bug

#78 design: login, join view
  src/main/java/kr/co/dbcs/controller/MailServiceRestController.java
  src/main/java/kr/co/dbcs/service/MailServiceImpl.java
  src/main/webapp/WEB-INF/css/member/login.css
  src/main/webapp/WEB-INF/css/member/login.css.map
  src/main/webapp/WEB-INF/css/member/login.scss
  src/main/webapp/WEB-INF/js/login.js
  src/main/webapp/WEB-INF/js/member/join.js
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
  src/main/webapp/WEB-INF/views/login.jsp
Labels: enhancement

#79 feat: add member search for note with trie data structure.
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/controller/NoteController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/mapper/NoteMapper.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/java/kr/co/dbcs/service/NoteService.java
  src/main/webapp/WEB-INF/css/note/note.css
  src/main/webapp/WEB-INF/js/note/note.js
  src/main/webapp/WEB-INF/views/note/note.jsp
Labels: enhancement

#80 fix: restore files
  src/main/java/kr/co/dbcs/controller/AdminController.java
  src/main/java/kr/co/dbcs/controller/MailServiceRestController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/controller/NoteController.java
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/admin/stat.jsp
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/search.jsp
  src/main/webapp/WEB-INF/views/board/update.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/board/write.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/member/chat.html
  src/main/webapp/WEB-INF/views/member/chat.jsp
  src/main/webapp/WEB-INF/views/member/join.jsp
  src/main/webapp/WEB-INF/views/member/movieList.jsp
  src/main/webapp/WEB-INF/views/member/movieView.jsp
  src/main/webapp/WEB-INF/views/member/myLoved.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
  src/main/webapp/WEB-INF/views/note/note.jsp
Labels: bug

#81 fix(board): board paging hot-fix
  src/main/java/kr/co/dbcs/config/MailConfig.java
  src/main/java/kr/co/dbcs/provider/BoardSqlProvider.java
Labels: bug

#82 feat: add index page's movie background
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/images/main.mp4
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/index.jsp
Labels: enhancement

#83 ci(git-secret): encode mail properties
  .gitignore
  .gitsecret/paths/mapping.cfg
  src/main/java/kr/co/dbcs/config/MailConfig.java
  src/main/resources/Wallet_V7LAPSS78F8HACJD/README.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.pem.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/keystore.jks.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ojdbc.properties.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/sqlnet.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/tnsnames.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/truststore.jks.secret
  src/main/resources/db.properties.secret
  src/main/resources/mail.properties.secret
Labels: enhancement

#84 fix(ci): fix git secret file
  .gitsecret/paths/mapping.cfg
  src/main/resources/Wallet_V7LAPSS78F8HACJD/README.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.pem.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/keystore.jks.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ojdbc.properties.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/sqlnet.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/tnsnames.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/truststore.jks.secret
  src/main/resources/db.properties.secret
  src/main/resources/mail.properties.secret
Labels: bug

#85 fix(mail): set ssl protocols
  .gitsecret/paths/mapping.cfg
  src/main/java/kr/co/dbcs/config/MailConfig.java
  src/main/resources/Wallet_V7LAPSS78F8HACJD/README.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.pem.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/keystore.jks.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ojdbc.properties.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/sqlnet.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/tnsnames.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/truststore.jks.secret
  src/main/resources/db.properties.secret
  src/main/resources/mail.properties.secret
Labels: bug

#86 fix: main header css and show all people on search list first in note
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/index.css.map
  src/main/webapp/WEB-INF/css/index.scss
  src/main/webapp/WEB-INF/css/member/login.css
  src/main/webapp/WEB-INF/css/member/login.css.map
  src/main/webapp/WEB-INF/css/member/login.scss
  src/main/webapp/WEB-INF/css/member/userHeader.css
  src/main/webapp/WEB-INF/css/member/userHeader.css.map
  src/main/webapp/WEB-INF/css/member/userHeader.scss
  src/main/webapp/WEB-INF/js/note/note.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
Labels: enhancement

#87 fix: minor fix
  .gitsecret/paths/mapping.cfg
  src/main/resources/Wallet_V7LAPSS78F8HACJD/README.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.pem.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/keystore.jks.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ojdbc.properties.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/sqlnet.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/tnsnames.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/truststore.jks.secret
  src/main/resources/db.properties.secret
  src/main/resources/mail.properties.secret
Labels: bug

#88 design: board view
  src/main/webapp/WEB-INF/css/board/list.css
  src/main/webapp/WEB-INF/css/board/list.css.map
  src/main/webapp/WEB-INF/css/board/list.scss
  src/main/webapp/WEB-INF/css/board/view.css
  src/main/webapp/WEB-INF/css/board/view.scss
  src/main/webapp/WEB-INF/images/check.png
  src/main/webapp/WEB-INF/images/delete.png
  src/main/webapp/WEB-INF/images/megaphone.png
  src/main/webapp/WEB-INF/images/replyuser.png
  src/main/webapp/WEB-INF/images/update.png
  src/main/webapp/WEB-INF/images/user.png
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
Labels: enhancement

#91 feat: sending data for ticket is now object of company
  src/main/java/kr/co/dbcs/controller/BoardController.java
  src/main/java/kr/co/dbcs/controller/MovieController.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/member/ticket.css
  src/main/webapp/WEB-INF/css/member/ticket.scss
  src/main/webapp/WEB-INF/js/member/ticket.js
  src/main/webapp/WEB-INF/views/board/search.jsp
  src/main/webapp/WEB-INF/views/board/view.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/member/ticket.jsp
Labels: enhancement

#92 feat: add my reply list page
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/ReplyMapper.java
  src/main/java/kr/co/dbcs/model/MyReplyVO.java
  src/main/java/kr/co/dbcs/provider/ReplySqlProvider.java
  src/main/java/kr/co/dbcs/service/ReplyService.java
  src/main/java/kr/co/dbcs/service/ReplyServiceImpl.java
  src/main/webapp/WEB-INF/css/member/replyList.css
  src/main/webapp/WEB-INF/css/member/replyList.scss
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/member/replyList.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#95 fix: session invalidate after member resign.
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/webapp/WEB-INF/js/member/update.js
Labels: enhancement

#97 design: note view
  src/main/webapp/WEB-INF/css/note/note.css
  src/main/webapp/WEB-INF/views/note/note.jsp
Labels: enhancement

#98 design: myPage view
  src/main/webapp/WEB-INF/css/member/myPage.css
  src/main/webapp/WEB-INF/css/member/myPage.css.map
  src/main/webapp/WEB-INF/css/member/myPage.scss
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#99 feat(security): enable https protocol
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/config/WebConfig.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/js/index.js
Labels: enhancement

#101 fix(security): https protocol mapping
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
Labels: bug

#102 design: movieList view
  src/main/webapp/WEB-INF/css/member/movieList.css
  src/main/webapp/WEB-INF/css/member/movieList.css.map
  src/main/webapp/WEB-INF/css/member/movieList.scss
  src/main/webapp/WEB-INF/images/heart.png
  src/main/webapp/WEB-INF/views/member/movieList.jsp
  src/main/webapp/WEB-INF/views/member/movieSearch.jsp
  src/main/webapp/WEB-INF/views/member/myLoved.jsp
Labels: enhancement

#103 feat: 비밀번호 재설정
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/MailServiceRestController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/mapper/PwdResetQueueMapper.java
  src/main/java/kr/co/dbcs/model/PwdResetQueueVO.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/provider/PwdResetQueueProvider.java
  src/main/java/kr/co/dbcs/service/CRUDService.java
  src/main/java/kr/co/dbcs/service/MailService.java
  src/main/java/kr/co/dbcs/service/MailServiceImpl.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/board/write.css
  src/main/webapp/WEB-INF/css/board/write.css.map
  src/main/webapp/WEB-INF/css/board/write.scss
  src/main/webapp/WEB-INF/css/member/resetPwd.css
  src/main/webapp/WEB-INF/css/member/resetPwd.scss
  src/main/webapp/WEB-INF/images/favicon.ico
  src/main/webapp/WEB-INF/js/member/resetPwd.js
  src/main/webapp/WEB-INF/js/member/resetPwdMail.js
  src/main/webapp/WEB-INF/views/board/write.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/member/resetPwd.jsp
  src/main/webapp/WEB-INF/views/member/resetPwdMail.jsp
Labels: enhancement

#104 fix: get member list except self in note
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
Labels: bug

#105 feat(board): show member images on board and reply
  src/main/java/kr/co/dbcs/model/BoardVO.java
  src/main/java/kr/co/dbcs/model/ReplyVO.java
  src/main/java/kr/co/dbcs/provider/BoardSqlProvider.java
  src/main/java/kr/co/dbcs/provider/ReplySqlProvider.java
  src/main/webapp/WEB-INF/views/board/view.jsp
Labels: enhancement

#106 fix(member): delete profile image session bug fi
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/model/ReplyVO.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: bug

#107 fix: board write fix
  src/main/webapp/WEB-INF/css/board/write.css
  src/main/webapp/WEB-INF/views/board/write.jsp
Labels: bug

#108 fix : main page's movie detail link error, open chat protocol and port number
  src/main/webapp/WEB-INF/js/index.js
  src/main/webapp/WEB-INF/js/member/chat.js
Labels: bug
