Repository Engineering-Excellence/CineVerse, pull requests merged in 2023-08, with the labels that each got.

#1 doc(ddl): add member ddl
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/HomeController.java
  src/main/resources/sql/member.sql
Labels: documentation

#2 feat(member): add controller, service, mapper
  src/main/java/kr/co/dbcs/config/ServletConfig.java
  src/main/java/kr/co/dbcs/controller/HomeController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/service/CRUDService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/views/member/join.jsp
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#3 feat: add member join temporary
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/service/CRUDService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/resources/sql/member.sql
  src/main/webapp/WEB-INF/views/member/join.jsp
Labels: enhancement

#5 fix(test): add config directory
  .gitsecret/paths/mapping.cfg
  pom.xml
  src/main/java/kr/co/dbcs/config/RootConfig.java
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/resources/Wallet_V7LAPSS78F8HACJD/README.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/cwallet.sso.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.lck.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.p12.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ewallet.pem.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/keystore.jks.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/ojdbc.properties.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/sqlnet.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/tnsnames.ora.secret
  src/main/resources/Wallet_V7LAPSS78F8HACJD/truststore.jks.secret
  src/main/resources/db.properties.secret
  src/main/webapp/WEB-INF/views/index.jsp
  src/test/java/kr/co/dbcs/config/DataSourceTest.java
Labels: bug

#8 feat: add code for member update process.
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/model/Member.java
  src/main/java/kr/co/dbcs/model/MemberVO.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/views/member/update.jsp
Labels: enhancement

#10 doc(ddl): add auth table
  pom.xml
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/model/AuthVO.java
  src/main/java/kr/co/dbcs/model/CustomUser.java
  src/main/java/kr/co/dbcs/model/MemberVO.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
  src/main/java/kr/co/dbcs/service/CustomUserDetailsService.java
  src/main/java/kr/co/dbcs/service/MemberService.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/resources/sql/auth.sql
  src/main/resources/sql/member.sql
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/member/join.jsp
Labels: documentation

#11 fix(security): multi authority bug fix
  src/main/java/kr/co/dbcs/mapper/MemberMapper.java
  src/main/java/kr/co/dbcs/provider/MemberSqlProvider.java
Labels: bug

#13 refactor: convert login, join form from html to jsp.
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/webapp/WEB-INF/css/member/join.css
  src/main/webapp/WEB-INF/css/member/join.scss
  src/main/webapp/WEB-INF/css/member/userMain.css
  src/main/webapp/WEB-INF/html/user/join.html
  src/main/webapp/WEB-INF/html/user/login.html
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/footer.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/join.jsp
Labels: enhancement

#19 feat: add join page's front logic
  src/main/java/kr/co/dbcs/config/SecurityConfig.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/java/kr/co/dbcs/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/css/member/join.css
  src/main/webapp/WEB-INF/css/member/join.scss
  src/main/webapp/WEB-INF/css/member/login.css
  src/main/webapp/WEB-INF/css/member/login.scss
  src/main/webapp/WEB-INF/js/member/join.js
  src/main/webapp/WEB-INF/js/validation.js
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/join.jsp
Labels: enhancement

#20 feat: add admin controller
  src/main/java/kr/co/dbcs/controller/AdminController.java
  src/main/java/kr/co/dbcs/controller/HomeController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/webapp/WEB-INF/js/member/join.js
  src/main/webapp/WEB-INF/views/admin/home.jsp
  src/main/webapp/WEB-INF/views/member/home.jsp
Labels: enhancement

#21 feat(controller): Page branching based on user permissions
  src/main/java/kr/co/dbcs/controller/AdminController.java
  src/main/java/kr/co/dbcs/controller/HomeController.java
  src/main/java/kr/co/dbcs/controller/MemberController.java
  src/main/webapp/WEB-INF/js/login.js
  src/main/webapp/WEB-INF/js/member/join.js
  src/main/webapp/WEB-INF/js/validation.js
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/layouts/header.jsp
  src/main/webapp/WEB-INF/views/member/join.jsp
  src/main/webapp/WEB-INF/views/member/movieDetail.jsp
  src/main/webapp/WEB-INF/views/member/movieList.jsp
  src/main/webapp/WEB-INF/views/member/userMain.jsp
  src/test/java/kr/co/dbcs/service/MemberServiceImplTest.java
Labels: enhancement
